/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Libreria.Cliente;
import Libreria.Compra;
import Libreria.TipoCliente;

/**
 *
 * @author Administrador
 */
public class FormGestCompra extends javax.swing.JFrame {

    /**
     * Creates new form FormGestCompra
     */
    public FormGestCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_run = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_apepat = new javax.swing.JTextField();
        tf_apemat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_tipocliente = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        tf_montcomp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_totdes = new javax.swing.JTextField();
        tf_subtot = new javax.swing.JTextField();
        tf_iva = new javax.swing.JTextField();
        tf_pago = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        bt_consultar = new javax.swing.JButton();
        bt_restablecer = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Compra");

        jLabel1.setText("RUN");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Tipo Cliente");

        cb_tipocliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Normal", "Silver", "Gold", "Premium" }));
        cb_tipocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipoclienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Monto Compra");

        jLabel7.setText("Total Descuento");

        jLabel8.setText("SubTotal");

        jLabel9.setText("I.V.A");

        jLabel10.setText("Pago");

        tf_totdes.setEditable(false);
        tf_totdes.setBackground(new java.awt.Color(204, 204, 204));

        tf_subtot.setEditable(false);
        tf_subtot.setBackground(new java.awt.Color(204, 204, 204));

        tf_iva.setEditable(false);
        tf_iva.setBackground(new java.awt.Color(204, 204, 204));

        tf_pago.setEditable(false);
        tf_pago.setBackground(new java.awt.Color(204, 204, 204));

        bt_consultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\bellavista_lab303\\Desktop\\tarea domingo\\tareauml-master\\gwget-icono-3905-48.png")); // NOI18N
        bt_consultar.setText("CONSULTAR");
        bt_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultarActionPerformed(evt);
            }
        });

        bt_restablecer.setIcon(new javax.swing.ImageIcon("C:\\Users\\bellavista_lab303\\Desktop\\tarea domingo\\tareauml-master\\a-doble-flecha-izquierda-x-icono-5602-48.png")); // NOI18N
        bt_restablecer.setText("RESTABLECER");
        bt_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_restablecerActionPerformed(evt);
            }
        });

        bt_salir.setIcon(new javax.swing.ImageIcon("C:\\Users\\bellavista_lab303\\Desktop\\tarea domingo\\tareauml-master\\la-flecha-verde-de-la-derecha-icono-8267-48.png")); // NOI18N
        bt_salir.setText("SALIR");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Gestion de Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_totdes, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(tf_subtot)
                                    .addComponent(tf_iva)
                                    .addComponent(tf_pago)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bt_consultar)
                                .addGap(18, 18, 18)
                                .addComponent(bt_restablecer)
                                .addGap(18, 18, 18)
                                .addComponent(bt_salir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_run)
                            .addComponent(tf_nombre)
                            .addComponent(tf_apemat)
                            .addComponent(tf_apepat)
                            .addComponent(cb_tipocliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(tf_montcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_apepat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apemat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tipocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_montcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_totdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_subtot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_consultar)
                    .addComponent(bt_restablecer)
                    .addComponent(bt_salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_restablecerActionPerformed
        // TODO add your handling code here:
        tf_run.setText("");
        tf_nombre.setText("");
        tf_apepat.setText("");
        tf_apemat.setText("");
        cb_tipocliente.setSelectedIndex(0);
        tf_montcomp.setText("");


    }//GEN-LAST:event_bt_restablecerActionPerformed

    private void cb_tipoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tipoclienteActionPerformed

    private void bt_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultarActionPerformed
        // Primero se crea un cliente y se inicializan sus datos.
        Cliente cliente = new Cliente();
        cliente.setRun(tf_run.getText());
        cliente.setNombre(tf_nombre.getText());
        cliente.setApPaterno(tf_apepat.getText());
        cliente.setApMaterno(tf_apemat.getText());
        
        // Se determina el tipo de cliente.
        String tipoCliente = cb_tipocliente.getSelectedItem().toString();
        cliente.setTipoCliente(TipoCliente.valueOf(tipoCliente));
        
        // Una vez inicializado el cliente, se crea una nueva compra y se
        // inicializa su cliente y su monto.
        Compra compra = new Compra();
        compra.setCliente(cliente);
        compra.setMonto(Integer.parseInt(tf_montcomp.getText()));

        // Una vez inicializado el monto, se pueden determinar los valores
        // necesarios para completar los datos de la compra.
        tf_totdes.setText(String.valueOf(compra.obtenerDescuento()));
        tf_subtot.setText(String.valueOf(compra.obtenerSubtotal()));
        tf_iva.setText(String.valueOf(compra.obtenerIVA()));
        tf_pago.setText(String.valueOf(compra.obtenerPago()));
    }//GEN-LAST:event_bt_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGestCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGestCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGestCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGestCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGestCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consultar;
    private javax.swing.JButton bt_restablecer;
    private javax.swing.JButton bt_salir;
    private javax.swing.JComboBox<String> cb_tipocliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tf_apemat;
    private javax.swing.JTextField tf_apepat;
    private javax.swing.JTextField tf_iva;
    private javax.swing.JTextField tf_montcomp;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pago;
    private javax.swing.JTextField tf_run;
    private javax.swing.JTextField tf_subtot;
    private javax.swing.JTextField tf_totdes;
    // End of variables declaration//GEN-END:variables
}
